#                   __ 
#   ___ ___  _ __  / _|
#  / __/ _ \| '_ \| |_ 
# | (_| (_) | | | |  _|
#  \___\___/|_| |_|_|  

add_newline = true
#left side
format = """$directory$character"""
#right side
right_format = """$all"""


[character]
format = "[❯ ](#FF0066)"

[git_branch]
disabled = false
format = "[$symbol$branch]($style) "
style = "bold dimmed green"
symbol = " "

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
style = "bold green"

